"use client";
import {RefreshCw,Search,AlertTriangle,CheckCircle2,Clock3} from "lucide-react";
export function PageTitle({title,sub}:{title:string;sub?:string}){return <div className="mb-6"><h1 className="text-2xl md:text-3xl font-semibold tracking-tight">{title}</h1>{sub&&<p className="text-sm text-slate-500 mt-1">{sub}</p>}</div>}
export function Card({children,className=""}:{children:React.ReactNode;className?:string}){return <div className={`panel rounded-lg ${className}`}>{children}</div>}
export function Kpi({label,value,unit,status}:{label:string;value:React.ReactNode;unit?:string;status?:string}){return <Card className="p-4"><div className="text-[10px] tracking-[.16em] text-slate-500 uppercase">{label}</div><div className="mt-3 flex items-end gap-2"><span className="text-2xl font-semibold mono">{value}</span>{unit&&<span className="text-xs text-slate-500 mb-1">{unit}</span>}</div>{status&&<div className="mt-2 text-[11px] text-slate-500">{status}</div>}</Card>}
export function Status({value}:{value?:string}){const v=(value||"UNKNOWN").toUpperCase();const critical=v.includes("CRIT")||v.includes("OFFLINE")||v.includes("HIGH")||v.includes("UNSAFE");const warn=v.includes("WARN")||v.includes("MEDIUM")||v.includes("CAUTION");return <span className={`inline-flex items-center gap-1.5 text-[11px] ${critical?"text-red-300":warn?"text-amber-300":"text-emerald-300"}`}><span className={`h-1.5 w-1.5 rounded-full ${critical?"bg-red-400":warn?"bg-amber-400":"bg-emerald-400"}`}/>{v}</span>}
export function ProgressBar({percent,critical,warn}:{percent:number;critical?:boolean;warn?:boolean}){const p=Math.max(0,Math.min(100,percent));const color=critical?"bg-red-400":warn?"bg-amber-400":"bg-emerald-400";return <div className="h-1.5 w-full rounded-full bg-[#1e2933] overflow-hidden"><div className={`h-full ${color} transition-all`} style={{width:`${p}%`}}/></div>}
export function Loading(){return <div className="panel rounded-lg p-10 text-center text-slate-500"><RefreshCw className="mx-auto mb-3 animate-spin" size={20}/>Loading backend data…</div>}
export function ErrorBox({onRetry}:{onRetry:()=>void}){return <div className="panel rounded-lg p-10 text-center"><AlertTriangle className="mx-auto mb-3 text-amber-300" size={22}/><div className="font-medium">Backend unavailable</div><p className="text-sm text-slate-500 mt-1">Unable to fetch data from the FastAPI service.</p><button onClick={onRetry} className="mt-4 px-4 py-2 text-xs border border-slate-600 rounded hover:bg-white/5">RETRY</button></div>}
export function SearchBox({value,onChange}:{value:string;onChange:(v:string)=>void}){return <div className="flex items-center gap-2 panel rounded-md px-3 h-10"><Search size={15} className="text-slate-500"/><input value={value} onChange={e=>onChange(e.target.value)} placeholder="Search wells…" className="bg-transparent outline-none text-sm w-full"/></div>}
export function Empty({text="No data available"}:{text?:string}){return <div className="panel p-10 text-center text-sm text-slate-500"><Clock3 className="mx-auto mb-3 opacity-50" size={20}/>{text}</div>}
