"use client";import {useEffect,useState} from "react";import {useParams} from "next/navigation";import Link from "next/link";import {api} from "@/lib/api";import {createWellSocket} from "@/lib/websocket";import {PageTitle,Card,Kpi,Status,Loading,ErrorBox} from "@/components/ui";import {ProductionChart,DynacardChart} from "@/components/charts";
const v=(o:any,...k:string[])=>k.map(x=>o?.[x]).find(x=>x!==undefined&&x!==null)??"—";
export default function WellDetail(){const p=useParams();const id=decodeURIComponent(String(p.id));const[data,setData]=useState<any>(null),[snap,setSnap]=useState<any>(null),[series,setSeries]=useState<any[]>([]),[dyn,setDyn]=useState<any[]>([]),[live,setLive]=useState<any>(null),[ws,setWs]=useState("connecting"),[err,setErr]=useState(false);
 const load=()=>Promise.all([api.well(id),api.snapshot(id),api.series(id),api.dynacard(id)]).then(([w,s,se,d])=>{setData(w);setSnap(s);setSeries(Array.isArray(se)?se:(se?.data||se?.series||[]));setDyn(Array.isArray(d)?d:(d?.data||d?.points||[]))}).catch(()=>setErr(true));
 useEffect(()=>{load();const stop=createWellSocket(id,x=>setLive(x),s=>setWs(s));return stop},[id]);
 if(err)return <ErrorBox onRetry={()=>{setErr(false);load()}}/>;if(!data&&!snap)return <Loading/>;
 const x={...(data||{}),...(snap||{})};return <><div className="flex items-start justify-between"><PageTitle title={id.toUpperCase()} sub="Well digital twin / current operating snapshot"/><div className="text-right text-xs"><Status value={String(v(data,"status"))}/><div className="mt-2 flex items-center gap-2 text-cyan-300"><span className={`h-2 w-2 rounded-full ${ws==="open"?"bg-cyan-300 animate-pulse":"bg-slate-600"}`}/>{ws==="open"?"SIMULATED LIVE FEED":"LIVE FEED "+ws.toUpperCase()}</div></div></div>
 <div className="grid grid-cols-2 lg:grid-cols-5 gap-3"><Kpi label="Production" value={v(x,"production","oil_rate")}/><Kpi label="Pressure" value={v(x,"pressure")}/><Kpi label="Temperature" value={v(x,"temperature")}/><Kpi label="Water Cut" value={v(x,"water_cut")}/><Kpi label="Live Flow" value={v(live,"flow","production")}/></div>
 <div className="grid grid-cols-2 lg:grid-cols-5 gap-3 mt-3"><Kpi label="Tank Level" value={v(live,"tank_level")+"%"}/><Kpi label="Vibration" value={v(live,"vibration")+" mm/s"}/><Kpi label="Pump Load" value={v(live,"pump_load")+"%"}/><Kpi label="Motor Current" value={v(live,"motor_current")+" A"}/></div>
 <div className="grid xl:grid-cols-[1.5fr_1fr] gap-4 mt-4"><Card className="p-5"><div className="flex justify-between mb-4"><div className="font-semibold text-sm">90-DAY PRODUCTION</div><span className="text-[10px] text-slate-500">BACKEND SERIES</span></div><ProductionChart data={series}/></Card><Card className="p-5"><div className="font-semibold text-sm mb-4">CURRENT PARAMETERS</div><div className="space-y-3 text-xs">{Object.entries(data||{}).filter(([k])=>/css|srp|spm|stroke|soak|injection/i.test(k)).slice(0,10).map(([k,val])=><div className="flex justify-between border-b border-[#1e2933] pb-2" key={k}><span className="text-slate-500">{k}</span><span className="mono">{String(val)}</span></div>)}</div><div className="mt-5"><Link href="/simulation" className="text-xs text-cyan-300 hover:underline">Open what-if simulation →</Link></div></Card></div>
 <Card className="p-5 mt-4"><div className="flex items-center justify-between mb-3"><div><div className="font-semibold text-sm">DYNAMOMETER CARD</div><div className="text-xs text-slate-500 mt-1">Actual backend dynacard points</div></div></div>{dyn.length?<DynacardChart data={dyn}/>:<div className="h-[330px] flex items-center justify-center text-sm text-slate-600">No dynamometer data available</div>}</Card>
 <div className="mt-4 text-[10px] text-slate-600">Engineering-plausible demonstration model. Results are not field-calibrated and should not be used for real operational decisions without engineering validation.</div>
 </>}
